chore: sunset referral rewards
across-protocol/frontend-v3 pull request #1036
Opened 2024-05-14 15:25 UTC by dohaki

Closes ACX-2048

2024-05-15 12:18 UTC, amateima commented on src/views/RewardsProgram/ACXReferralsProgram.tsx
> +            </LearnMoreLink>
This can point to https://snapshot.org/#/acrossprotocol.eth/proposal/0xa8af5c0d2a9caea7057900744cfde4ee28529300f947abf7696856216a97f8eb

2024-05-15 15:40 UTC, james-a-morris approved these changes

2024-05-16 06:38 UTC, amateima requested changes
Seems there's a merge conflict

2024-05-16 06:41 UTC, amateima approved these changes

2024-05-16 06:56 UTC, merged